//<![CDATA[
var gamebirdDataArr = [[
    "Brent Goose",
"Red-breasted Goose",
"Canada Goose",
"Barnacle Goose",
"Cackling Goose",
"Snow Goose",
"Greylag Goose",
"Taiga Bean Goose",
"Pink-footed Goose",
"Tundra Bean Goose",
"White-fronted Goose",
"Lesser White-fronted Goose",
"Mute Swan",
"Bewick's Swan",
"Whooper Swan",
"Egyptian Goose",
"Shelduck",
"Ruddy Shelduck",
"Mandarin",
"Baikal Teal",
"Garganey",
"Blue-winged Teal",
"Shoveler",
"Gadwall",
"Wigeon",
"American Wigeon",
"Mallard",
"Black Duck",
"Pintail",
"Teal",
"Green-winged Teal",
"Red-crested Pochard",
"Canvasback",
"Redhead",
"Pochard",
"Ferruginous Duck",
"Ring-necked Duck",
"Tufted Duck",
"Scaup",
"Lesser Scaup",
"Steller's Eider",
"King Eider",
"Eider",
"Harlequin Duck",
"Surf Scoter",
"Velvet Scoter",
"White-winged Scoter",
"Common Scoter",
"Black Scoter",
"Long-tailed Duck",
"Bufflehead",
"Goldeneye",
"Barrow's Goldeneye",
"Smew",
"Hooded Merganser",
"Goosander",
"Red-breasted Merganser",
"Ruddy Duck",
"Capercaillie",
"Black Grouse",
"Ptarmigan",
"Red Grouse",
"Red-legged Partridge",
"Grey Partridge",
"Quail",
"Pheasant",
"Golden Pheasant",
"Lady Amherst's Pheasant",
"Red-throated Diver",
"Black-throated Diver",
"Pacific Diver",
"Great Northern Diver",
"White-billed Diver",
"Wilson's Petrel",
"White-faced Storm Petrel",
"Black-browed Albatross",
"Atlantic Yellow-nosed Albatross",
"Storm Petrel",
"Swinhoe's Petrel",
"Leach's Petrel",
"Fulmar",
"Black-capped Petrel",
"Scopoli's Shearwater",
"Cory's Shearwater",
"Sooty Shearwater",
"Great Shearwater",
"Manx Shearwater",
"Yelkouan Shearwater",
"Balearic Shearwater",
"Barolo Shearwater",
"Little Grebe",
"Pied-billed Grebe",
"Red-necked Grebe",
"Great Crested Grebe",
"Slavonian Grebe",
"Black-necked Grebe",
"Red-billed Tropicbird",
"Black Stork",
"White Stork",
"Glossy Ibis",
"Spoonbill",
"Bittern",
"American Bittern",
"Little Bittern",
"Night-heron",
"Green Heron",
"Squacco Heron",
"Chinese Pond Heron",
"Cattle Egret",
"Grey Heron",
"Great Blue Heron",
"Purple Heron",
"Great White Egret",
"Snowy Egret",
"Little Egret",
"Ascension Frigatebird",
"Magnificent Frigatebird",
"Gannet",
"Red-footed Booby",
"Double-crested Cormorant",
"Shag",
"Cormorant",
"Osprey",
"Egyptian Vulture",
"Honey-buzzard",
"Short-toed Eagle",
"Spotted Eagle",
"Golden Eagle",
"Sparrowhawk",
"Goshawk",
"Marsh Harrier",
"Hen Harrier",
"Northern Harrier",
"Pallid Harrier",
"Montagu's Harrier",
"Red Kite",
"Black Kite",
"White-tailed Eagle",
"Rough-legged Buzzard",
"Buzzard",
"Great Bustard",
"Macqueen's Bustard",
"Little Bustard",
"Water Rail",
"Corncrake",
"Little Crake",
"Baillon's Crake",
"Spotted Crake",
"Sora Rail",
"Western Swamphen",
"Allen's Gallinule",
"American Purple Gallinule",
"Moorhen",
"Coot",
"American Coot",
"Sandhill Crane",
"Crane",
"Stone-curlew",
"Oystercatcher",
"Black-winged Stilt",
"Avocet",
"Lapwing",
"Sociable Plover",
"White-tailed Plover",
"Golden Plover",
"Pacific Golden Plover",
"American Golden Plover",
"Grey Plover",
"Ringed Plover",
"Semipalmated Plover",
"Little Ringed Plover",
"Killdeer",
"Kentish Plover",
"Lesser Sand Plover",
"Greater Sand Plover",
"Caspian Plover",
"Dotterel",
"Upland Sandpiper",
"Whimbrel",
"Little Whimbrel",
"Eskimo Curlew",
"Curlew",
"Bar-tailed Godwit",
"Black-tailed Godwit",
"Hudsonian Godwit",
"Turnstone",
"Great Knot",
"Knot",
"Ruff",
"Broad-billed Sandpiper",
"Sharp-tailed Sandpiper",
"Stilt Sandpiper",
"Curlew Sandpiper",
"Temminck's Stint",
"Long-toed Stint",
"Red-necked Stint",
"Sanderling",
"Dunlin",
"Purple Sandpiper",
"Baird's Sandpiper",
"Little Stint",
"Least Sandpiper",
"White-rumped Sandpiper",
"Buff-breasted Sandpiper",
"Pectoral Sandpiper",
"Semipalmated Sandpiper",
"Western Sandpiper",
"Long-billed Dowitcher",
"Short-billed Dowitcher",
"Woodcock",
"Jack Snipe",
"Great Snipe",
"Snipe",
"Wilson's Snipe",
"Terek Sandpiper",
"Wilson's Phalarope",
"Red-necked Phalarope",
"Grey Phalarope",
"Common Sandpiper",
"Spotted Sandpiper",
"Green Sandpiper",
"Solitary Sandpiper",
"Grey-tailed Tattler",
"Lesser Yellowlegs",
"Redshank",
"Marsh Sandpiper",
"Wood Sandpiper",
"Spotted Redshank",
"Greenshank",
"Greater Yellowlegs",
"Cream-coloured Courser",
"Collared Pratincole",
"Oriental Pratincole",
"Black-winged Pratincole",
"Kittiwake",
"Ivory Gull",
"Sabine's Gull",
"Slender-billed Gull",
"Bonaparte's Gull",
"Black-headed Gull",
"Little Gull",
"Ross's Gull",
"Laughing Gull",
"Franklin's Gull",
"Audouin's Gull",
"Mediterranean Gull",
"Great Black-headed Gull",
"Common Gull",
"Ring-billed Gull",
"Great Black-backed Gull",
"Glaucous-winged Gull",
"Glaucous Gull",
"Iceland Gull",
"Herring Gull",
"American Herring Gull",
"Caspian Gull",
"Yellow-legged Gull",
"Slaty-backed Gull",
"Lesser Black-backed Gull",
"Gull-billed Tern",
"Caspian Tern",
"Royal Tern",
"Lesser Crested Tern",
"Sandwich Tern",
"Cabot's Tern",
"Elegant Tern",
"Little Tern",
"Least Tern",
"Aleutian Tern",
"Bridled Tern",
"Sooty Tern",
"Roseate Tern",
"Common Tern",
"Arctic Tern",
"Forster's Tern",
"Whiskered Tern",
"White-winged Black Tern",
"Black Tern",
"Great Skua",
"Pomarine Skua",
"Arctic Skua",
"Long-tailed Skua",
"Little Auk",
"Brünnich's Guillemot",
"Guillemot",
"Razorbill",
"Great Auk",
"Black Guillemot",
"Long-billed Murrelet",
"Ancient Murrelet",
"Puffin",
"Tufted Puffin",
"Pallas's Sandgrouse",
"Rock Dove",
"Stock Dove",
"Woodpigeon",
"Turtle Dove",
"Oriental Turtle Dove",
"Collared Dove",
"Mourning Dove",
"Great Spotted Cuckoo",
"Yellow-billed Cuckoo",
"Black-billed Cuckoo",
"Cuckoo",
"Barn Owl",
"Scops Owl",
"Snowy Owl",
"Tawny Owl",
"Hawk Owl",
"Little Owl",
"Tengmalm's Owl",
"Long-eared Owl",
"Short-eared Owl",
"Common Nighthawk",
"Red-necked Nightjar",
"Nightjar",
"Egyptian Nightjar",
"White-throated Needletail",
"Chimney Swift",
"Alpine Swift",
"Swift",
"Pallid Swift",
"Pacific Swift",
"Little Swift",
"Roller",
"Kingfisher",
"Belted Kingfisher",
"Blue-cheeked Bee-eater",
"Bee-eater",
"Hoopoe",
"Wryneck",
"Yellow-bellied Sapsucker",
"Lesser Spotted Woodpecker",
"Great Spotted Woodpecker",
"Green Woodpecker",
"Lesser Kestrel",
"Kestrel",
"American Kestrel",
"Red-footed Falcon",
"Amur Falcon",
"Eleonora's Falcon",
"Merlin",
"Hobby",
"Gyrfalcon",
"Peregrine",
"Ring-necked Parakeet",
"Eastern Phoebe",
"Acadian Flycatcher",
"Alder Flycatcher",
"Eastern Kingbird",
"Brown Shrike",
"Red-backed Shrike",
"Daurian Shrike",
"Turkestan Shrike",
"Long-tailed Shrike",
"Lesser Grey Shrike",
"Great Grey Shrike",
"Steppe Grey Shrike",
"Woodchat Shrike",
"Masked Shrike",
"Yellow-throated Vireo",
"Philadelphia Vireo",
"Red-eyed Vireo",
"Golden Oriole",
"Jay",
"Magpie",
"Nutcracker",
"Chough",
"Jackdaw",
"Rook",
"Carrion Crow",
"Hooded Crow",
"Raven",
"Waxwing",
"Cedar Waxwing",
"Coal Tit",
"Crested Tit",
"Marsh Tit",
"Willow Tit",
"Blue Tit",
"Great Tit",
"Penduline Tit",
"Bearded Tit",
"Woodlark",
"White-winged Lark",
"Skylark",
"Crested Lark",
"Shore Lark",
"Short-toed Lark",
"Bimaculated Lark",
"Calandra Lark",
"Black Lark",
"Lesser Short-toed Lark",
"Sand Martin",
"Tree Swallow",
"Purple Martin",
"Swallow",
"Crag Martin",
"House Martin",
"Red-rumped Swallow",
"American Cliff Swallow",
"Cetti's Warbler",
"Long-tailed Tit",
"Willow Warbler",
"Chiffchaff",
"Iberian Chiffchaff",
"Western Bonelli's Warbler",
"Eastern Bonelli's Warbler",
"Wood Warbler",
"Dusky Warbler",
"Radde's Warbler",
"Pallas's Warbler",
"Yellow-browed Warbler",
"Hume's Warbler",
"Arctic Warbler",
"Green Warbler",
"Greenish Warbler",
"Two-barred Greenish Warbler",
"Pale-legged Leaf Warbler",
"Eastern Crowned Warbler",
"Great Reed Warbler",
"Aquatic Warbler",
"Sedge Warbler",
"Paddyfield Warbler",
"Blyth's Reed Warbler",
"Reed Warbler",
"Marsh Warbler",
"Thick-billed Warbler",
"Booted Warbler",
"Sykes' Warbler",
"Eastern Olivaceous Warbler",
"Olive-tree Warbler",
"Melodious Warbler",
"Icterine Warbler",
"Grasshopper Warbler",
"River Warbler",
"Savi's Warbler",
"Lanceolated Warbler",
"Pallas's Grasshopper Warbler",
"Fan-tailed Warbler",
"Blackcap",
"Garden Warbler",
"Barred Warbler",
"Lesser Whitethroat",
"Western Orphean Warbler",
"Desert Warbler",
"Whitethroat",
"Dartford Warbler",
"Marmora's Warbler",
"Spectacled Warbler",
"Subalpine Warbler",
"Moltoni's Subalpine Warbler",
"Sardinian Warbler",
"Rüppell's Warbler",
"Firecrest",
"Goldcrest",
"Wren",
"Nuthatch",
"Red-breasted Nuthatch",
"Wallcreeper",
"Treecreeper",
"Short-toed Treecreeper",
"Grey Catbird",
"Northern Mockingbird",
"Brown Thrasher",
"Rose-coloured Starling",
"Starling",
"Siberian Thrush",
"White's Thrush",
"Varied Thrush",
"Veery",
"Grey-cheeked Thrush",
"Swainson's Thrush",
"Hermit Thrush",
"Wood Thrush",
"Ring Ouzel",
"Blackbird",
"Eyebrowed Thrush",
"Black-throated Thrush",
"Red-throated Thrush",
"Naumann's Thrush",
"Dusky Thrush",
"Fieldfare",
"Redwing",
"Song Thrush",
"Mistle Thrush",
"American Robin",
"Rufous-tailed Scrub Robin",
"Spotted Flycatcher",
"Asian Brown Flycatcher",
"Robin",
"Siberian Blue Robin",
"Rufous-tailed Robin",
"Bluethroat",
"Thrush Nightingale",
"Nightingale",
"White-throated Robin",
"Siberian Rubythroat",
"Red-flanked Bluetail",
"Pied Flycatcher",
"Collared Flycatcher",
"Red-breasted Flycatcher",
"Taiga Flycatcher",
"Black Redstart",
"Redstart",
"Moussier's Redstart",
"Rock Thrush",
"Blue Rock Thrush",
"Whinchat",
"Stonechat",
"Siberian Stonechat",
"Stejneger's Stonechat",
"Wheatear",
"Isabelline Wheatear",
"Desert Wheatear",
"Black-eared Wheatear",
"Pied Wheatear",
"White-crowned Black Wheatear",
"Dipper",
"House Sparrow",
"Spanish Sparrow",
"Tree Sparrow",
"Rock Sparrow",
"Alpine Accentor",
"Siberian Accentor",
"Dunnock",
"Yellow Wagtail",
"Eastern Yellow Wagtail",
"Citrine Wagtail",
"Grey Wagtail",
"Pied Wagtail",
"Richard's Pipit",
"Blyth's Pipit",
"Tawny Pipit",
"Meadow Pipit",
"Tree Pipit",
"Olive-backed Pipit",
"Pechora Pipit",
"Red-throated Pipit",
"Buff-bellied Pipit",
"Water Pipit",
"Rock Pipit",
"Chaffinch",
"Brambling",
"Evening Grosbeak",
"Hawfinch",
"Pine Grosbeak",
"Bullfinch",
"Trumpeter Finch",
"Common Rosefinch",
"Greenfinch",
"Twite",
"Linnet",
"Common Redpoll",
"Lesser Redpoll",
"Arctic Redpoll",
"Parrot Crossbill",
"Scottish Crossbill",
"Crossbill",
"Two-barred Crossbill",
"Goldfinch",
"Citril Finch",
"Serin",
"Siskin",
"Ovenbird",
"Northern Waterthrush",
"Golden-winged Warbler",
"Black-and-white Warbler",
"Tennessee Warbler",
"Common Yellowthroat",
"Hooded Warbler",
"American Redstart",
"Cape May Warbler",
"Northern Parula",
"Magnolia Warbler",
"Bay-breasted Warbler",
"Blackburnian Warbler",
"Yellow Warbler",
"Chestnut-sided Warbler",
"Blackpoll Warbler",
"Yellow-rumped Warbler",
"Wilson's Warbler",
"Bobolink",
"Baltimore Oriole",
"Red-winged Blackbird",
"Brown-headed Cowbird",
"Corn Bunting",
"Yellowhammer",
"Pine Bunting",
"Rock Bunting",
"Ortolan Bunting",
"Cretzschmar's Bunting",
"Cirl Bunting",
"Chestnut-eared Bunting",
"Little Bunting",
"Yellow-browed Bunting",
"Rustic Bunting",
"Yellow-breasted Bunting",
"Chestnut Bunting",
"Black-headed Bunting",
"Black-faced Bunting",
"Pallas's Reed Bunting",
"Reed Bunting",
"Song Sparrow",
"White-crowned Sparrow",
"White-throated Sparrow",
"Dark-eyed Junco",
"Savannah Sparrow",
"Lark Sparrow",
"Eastern Towhee",
"Lapland Bunting",
"Snow Bunting",
"Summer Tanager",
"Scarlet Tanager",
"Rose-breasted Grosbeak",
"Indigo Bunting"],
//latin names 
["Branta bernicla",
"Branta ruficollis",
"Branta canadensis",
"Branta leucopsis",
"Branta hutchinsii",
"Anser caerulescens",
"Anser anser",
"Anser fabalis",
"Anser brachyrhynchus",
"Anser serrirostris",
"Anser albifrons",
"Anser erythropus",
"Cygnus olor",
"Cygnus columbianus",
"Cygnus cygnus",
"Alopochen aegyptiaca",
"Tadorna tadorna",
"Tadorna ferruginea",
"Aix galericulata",
"Sibirionetta formosa",
"Spatula querquedula",
"Spatula discors",
"Spatula clypeata",
"Mareca strepera",
"Mareca penelope",
"Mareca americana",
"Anas platyrhynchos",
"Anas rubripes",
"Anas acuta",
"Anas crecca",
"Anas carolinensis",
"Netta rufina",
"Aythya valisineria",
"Aythya americana",
"Aythya ferina",
"Aythya nyroca",
"Aythya collaris",
"Aythya fuligula",
"Aythya marila",
"Aythya affinis",
"Polysticta stelleri",
"Somateria spectabilis",
"Somateria mollissima",
"Histrionicus histrionicus",
"Melanitta perspicillata",
"Melanitta fusca",
"Melanitta deglandi",
"Melanitta nigra",
"Melanitta americana",
"Clangula hyemalis",
"Bucephala albeola",
"Bucephala clangula",
"Bucephala islandica",
"Mergellus albellus",
"Lophodytes cucullatus",
"Mergus merganser",
"Mergus serrator",
"Oxyura jamaicensis",
"Tetrao urogallus",
"Lyrurus tetrix",
"Lagopus muta",
"Lagopus lagopus",
"Alectoris rufa",
"Perdix perdix",
"Coturnix coturnix",
"Phasianus colchicus",
"Chrysolophus pictus",
"Chrysolophus amherstiae",
"Gavia stellata",
"Gavia arctica",
"Gavia pacifica",
"Gavia immer",
"Gavia adamsii",
"Oceanites oceanicus",
"Pelagodroma marina",
"Thalassarche melanophris",
"Thalassarche chlororhynchos",
"Hydrobates pelagicus",
"Oceanodroma monorhis",
"Oceanodroma leucorhoa",
"Fulmarus glacialis",
"Pterodroma hasitata",
"Calonectris diomedea",
"Calonectris borealis",
"Ardenna grisea",
"Ardenna gravis",
"Puffinus puffinus",
"Puffinus yelkouan",
"Puffinus mauretanicus",
"Puffinus baroli",
"Tachybaptus ruficollis",
"Podilymbus podiceps",
"Podiceps grisegena",
"Podiceps cristatus",
"Podiceps auritus",
"Podiceps nigricollis",
"Phaethon aethereus",
"Ciconia nigra",
"Ciconia ciconia",
"Plegadis falcinellus",
"Platalea leucorodia",
"Botaurus stellaris",
"Botaurus lentiginosus",
"Ixobrychus minutus",
"Nycticorax nycticorax",
"Butorides virescens",
"Ardeola ralloides",
"Ardeola bacchus",
"Bubulcus ibis",
"Ardea cinerea",
"Ardea herodias",
"Ardea purpurea",
"Ardea alba",
"Egretta thula",
"Egretta garzetta",
"Fregata aquila",
"Fregata magnificens",
"Morus bassanus",
"Sula sula",
"Phalacrocorax auritus",
"Phalacrocorax aristotelis",
"Phalacrocorax carbo",
"Pandion haliaetus",
"Neophron percnopterus",
"Pernis apivorus",
"Circaetus gallicus",
"Clanga clanga",
"Aquila chrysaetos",
"Accipiter nisus",
"Accipiter gentilis",
"Circus aeruginosus",
"Circus cyaneus",
"Circus hudsonius",
"Circus macrourus",
"Circus pygargus",
"Milvus milvus",
"Milvus migrans",
"Haliaeetus albicilla",
"Buteo lagopus",
"Buteo buteo",
"Otis tarda",
"Chlamydotis macqueenii",
"Tetrax tetrax",
"Rallus aquaticus",
"Crex crex",
"Porzana parva",
"Porzana pusilla",
"Porzana porzana",
"Porzana carolina",
"Porphyrio porphyrio",
"Porphyrio alleni",
"Porphyrio martinica",
"Gallinula chloropus",
"Fulica atra",
"Fulica americana",
"Antigone canadensis",
"Grus grus",
"Burhinus oedicnemus",
"Haematopus ostralegus",
"Himantopus himantopus",
"Recurvirostra avosetta",
"Vanellus vanellus",
"Vanellus gregarius",
"Vanellus leucurus",
"Pluvialis apricaria",
"Pluvialis fulva",
"Pluvialis dominica",
"Pluvialis squatarola",
"Charadrius hiaticula",
"Charadrius semipalmatus",
"Charadrius dubius",
"Charadrius vociferus",
"Charadrius alexandrinus",
"Charadrius mongolus",
"Charadrius leschenaultii",
"Charadrius asiaticus",
"Charadrius morinellus",
"Bartramia longicauda",
"Numenius phaeopus",
"Numenius minutus",
"Numenius borealis",
"Numenius arquata",
"Limosa lapponica",
"Limosa limosa",
"Limosa haemastica",
"Arenaria interpres",
"Calidris tenuirostris",
"Calidris canutus",
"Calidris pugnax",
"Calidris falcinellus",
"Calidris acuminata",
"Calidris himantopus",
"Calidris ferruginea",
"Calidris temminckii",
"Calidris subminuta",
"Calidris ruficollis",
"Calidris alba",
"Calidris alpina",
"Calidris maritima",
"Calidris bairdii",
"Calidris minuta",
"Calidris minutilla",
"Calidris fuscicollis",
"Calidris subruficollis",
"Calidris melanotos",
"Calidris pusilla",
"Calidris mauri",
"Limnodromus scolopaceus",
"Limnodromus griseus",
"Scolopax rusticola",
"Lymnocryptes minimus",
"Gallinago media",
"Gallinago gallinago",
"Gallinago delicata",
"Xenus cinereus",
"Phalaropus tricolor",
"Phalaropus lobatus",
"Phalaropus fulicarius",
"Actitis hypoleucos",
"Actitis macularius",
"Tringa ochropus",
"Tringa solitaria",
"Tringa brevipes",
"Tringa flavipes",
"Tringa totanus",
"Tringa stagnatilis",
"Tringa glareola",
"Tringa erythropus",
"Tringa nebularia",
"Tringa melanoleuca",
"Cursorius cursor",
"Glareola pratincola",
"Glareola maldivarum",
"Glareola nordmanni",
"Rissa tridactyla",
"Pagophila eburnea",
"Xema sabini",
"Chroicocephalus genei",
"Chroicocephalus philadelphia",
"Chroicocephalus ridibundus",
"Hydrocoloeus minutus",
"Rhodostethia rosea",
"Leucophaeus atricilla",
"Leucophaeus pipixcan",
"Ichthyaetus audouinii",
"Ichthyaetus melanocephalus",
"Ichthyaetus ichthyaetus",
"Larus canus",
"Larus delawarensis",
"Larus marinus",
"Larus glaucescens",
"Larus hyperboreus",
"Larus glaucoides",
"Larus argentatus",
"Larus smithsonianus",
"Larus cachinnans",
"Larus michahellis",
"Larus schistisagus",
"Larus fuscus",
"Gelochelidon nilotica",
"Hydroprogne caspia",
"Thalasseus maximus",
"Thalasseus bengalensis",
"Thalasseus sandvicensis",
"Thalasseus acuflavidus",
"Thalasseus elegans",
"Sternula albifrons",
"Sternula antillarum",
"Onychoprion aleuticus",
"Onychoprion anaethetus",
"Onychoprion fuscatus",
"Sterna dougallii",
"Sterna hirundo",
"Sterna paradisaea",
"Sterna forsteri",
"Chlidonias hybrida",
"Chlidonias leucopterus",
"Chlidonias niger",
"Stercorarius skua",
"Stercorarius pomarinus",
"Stercorarius parasiticus",
"Stercorarius longicaudus",
"Alle alle",
"Uria lomvia",
"Uria aalge",
"Alca torda",
"Pinguinus impennis",
"Cepphus grylle",
"Brachyramphus perdix",
"Synthliboramphus antiquus",
"Fratercula arctica",
"Fratercula cirrhata",
"Syrrhaptes paradoxus",
"Columba livia",
"Columba oenas",
"Columba palumbus",
"Streptopelia turtur",
"Streptopelia orientalis",
"Streptopelia decaocto",
"Zenaida macroura",
"Clamator glandarius",
"Coccyzus americanus",
"Coccyzus erythropthalmus",
"Cuculus canorus",
"Tyto alba",
"Otus scops",
"Bubo scandiacus",
"Strix aluco",
"Surnia ulula",
"Athene noctua",
"Aegolius funereus",
"Asio otus",
"Asio flammeus",
"Chordeiles minor",
"Caprimulgus ruficollis",
"Caprimulgus europaeus",
"Caprimulgus aegyptius",
"Hirundapus caudacutus",
"Chaetura pelagica",
"Tachymarptis melba",
"Apus apus",
"Apus pallidus",
"Apus pacificus",
"Apus affinis",
"Coracias garrulus",
"Alcedo atthis",
"Megaceryle alcyon",
"Merops persicus",
"Merops apiaster",
"Upupa epops",
"Jynx torquilla",
"Sphyrapicus varius",
"Dryobates minor",
"Dendrocopos major",
"Picus viridis",
"Falco naumanni",
"Falco tinnunculus",
"Falco sparverius",
"Falco vespertinus",
"Falco amurensis",
"Falco eleonorae",
"Falco columbarius",
"Falco subbuteo",
"Falco rusticolus",
"Falco peregrinus",
"Psittacula krameri",
"Sayornis phoebe",
"Empidonax virescens",
"Empidonax alnorum",
"Tyrannus tyrannus",
"Lanius cristatus",
"Lanius collurio",
"Lanius isabellinus",
"Lanius phoenicuroides",
"Lanius schach",
"Lanius minor",
"Lanius excubitor",
"Lanius pallidirostris",
"Lanius senator",
"Lanius nubicus",
"Vireo flavifrons",
"Vireo philadelphicus",
"Vireo olivaceus",
"Oriolus oriolus",
"Garrulus glandarius",
"Pica pica",
"Nucifraga caryocatactes",
"Pyrrhocorax pyrrhocorax",
"Coloeus monedula",
"Corvus frugilegus",
"Corvus corone",
"Corvus cornix",
"Corvus corax",
"Bombycilla garrulus",
"Bombycilla cedrorum",
"Periparus ater",
"Lophophanes cristatus",
"Poecile palustris",
"Poecile montanus",
"Cyanistes caeruleus",
"Parus major",
"Remiz pendulinus",
"Panurus biarmicus",
"Lullula arborea",
"Alauda leucoptera",
"Alauda arvensis",
"Galerida cristata",
"Eremophila alpestris",
"Calandrella brachydactyla",
"Melanocorypha bimaculata",
"Melanocorypha calandra",
"Melanocorypha yeltoniensis",
"Alaudala rufescens",
"Riparia riparia",
"Tachycineta bicolor",
"Progne subis",
"Hirundo rustica",
"Ptyonoprogne rupestris",
"Delichon urbicum",
"Cecropis daurica",
"Petrochelidon pyrrhonota",
"Cettia cetti",
"Aegithalos caudatus",
"Phylloscopus trochilus",
"Phylloscopus collybita",
"Phylloscopus ibericus",
"Phylloscopus bonelli",
"Phylloscopus orientalis",
"Phylloscopus sibilatrix",
"Phylloscopus fuscatus",
"Phylloscopus schwarzi",
"Phylloscopus proregulus",
"Phylloscopus inornatus",
"Phylloscopus humei",
"Phylloscopus borealis",
"Phylloscopus nitidus",
"Phylloscopus trochiloides",
"Phylloscopus plumbeitarsus",
"Phylloscopus tenellipes",
"Phylloscopus coronatus",
"Acrocephalus arundinaceus",
"Acrocephalus paludicola",
"Acrocephalus schoenobaenus",
"Acrocephalus agricola",
"Acrocephalus dumetorum",
"Acrocephalus scirpaceus",
"Acrocephalus palustris",
"Iduna aedon",
"Iduna caligata",
"Iduna rama",
"Iduna pallida",
"Hippolais olivetorum",
"Hippolais polyglotta",
"Hippolais icterina",
"Locustella naevia",
"Locustella fluviatilis",
"Locustella luscinioides",
"Locustella lanceolata",
"Locustella certhiola",
"Cisticola juncidis",
"Sylvia atricapilla",
"Sylvia borin",
"Sylvia nisoria",
"Sylvia curruca",
"Sylvia hortensis",
"Sylvia nana",
"Sylvia communis",
"Sylvia undata",
"Sylvia sarda",
"Sylvia conspicillata",
"Sylvia cantillans",
"Sylvia subalpina",
"Sylvia melanocephala",
"Sylvia ruppeli",
"Regulus ignicapilla",
"Regulus regulus",
"Troglodytes troglodytes",
"Sitta europaea",
"Sitta canadensis",
"Tichodroma muraria",
"Certhia familiaris",
"Certhia brachydactyla",
"Dumetella carolinensis",
"Mimus polyglottos",
"Toxostoma rufum",
"Pastor roseus",
"Sturnus vulgaris",
"Geokichla sibirica",
"Zoothera aurea",
"Ixoreus naevius",
"Catharus fuscescens",
"Catharus minimus",
"Catharus ustulatus",
"Catharus guttatus",
"Hylocichla mustelina",
"Turdus torquatus",
"Turdus merula",
"Turdus obscurus",
"Turdus atrogularis",
"Turdus ruficollis",
"Turdus naumanni",
"Turdus eunomus",
"Turdus pilaris",
"Turdus iliacus",
"Turdus philomelos",
"Turdus viscivorus",
"Turdus migratorius",
"Cercotrichas galactotes",
"Muscicapa striata",
"Muscicapa dauurica",
"Erithacus rubecula",
"Larvivora cyane",
"Larvivora sibilans",
"Luscinia svecica",
"Luscinia luscinia",
"Luscinia megarhynchos",
"Irania gutturalis",
"Calliope calliope",
"Tarsiger cyanurus",
"Ficedula hypoleuca",
"Ficedula albicollis",
"Ficedula parva",
"Ficedula albicilla",
"Phoenicurus ochruros",
"Phoenicurus phoenicurus",
"Phoenicurus moussieri",
"Monticola saxatilis",
"Monticola solitarius",
"Saxicola rubetra",
"Saxicola rubicola",
"Saxicola maurus",
"Saxicola stejnegeri",
"Oenanthe oenanthe",
"Oenanthe isabellina",
"Oenanthe deserti",
"Oenanthe hispanica",
"Oenanthe pleschanka",
"Oenanthe leucopyga",
"Cinclus cinclus",
"Passer domesticus",
"Passer hispaniolensis",
"Passer montanus",
"Petronia petronia",
"Prunella collaris",
"Prunella montanella",
"Prunella modularis",
"Motacilla flava",
"Motacilla tschutschensis",
"Motacilla citreola",
"Motacilla cinerea",
"Motacilla alba",
"Anthus richardi",
"Anthus godlewskii",
"Anthus campestris",
"Anthus pratensis",
"Anthus trivialis",
"Anthus hodgsoni",
"Anthus gustavi",
"Anthus cervinus",
"Anthus rubescens",
"Anthus spinoletta",
"Anthus petrosus",
"Fringilla coelebs",
"Fringilla montifringilla",
"Hesperiphona vespertina",
"Coccothraustes coccothraustes",
"Pinicola enucleator",
"Pyrrhula pyrrhula",
"Bucanetes githagineus",
"Carpodacus erythrinus",
"Chloris chloris",
"Linaria flavirostris",
"Linaria cannabina",
"Acanthis flammea",
"Acanthis cabaret",
"Acanthis hornemanni",
"Loxia pytyopsittacus",
"Loxia scotica",
"Loxia curvirostra",
"Loxia leucoptera",
"Carduelis carduelis",
"Carduelis citrinella",
"Serinus serinus",
"Spinus spinus",
"Seiurus aurocapilla",
"Parkesia noveboracensis",
"Vermivora chrysoptera",
"Mniotilta varia",
"Leiothlypis peregrina",
"Geothlypis trichas",
"Setophaga citrina",
"Setophaga ruticilla",
"Setophaga tigrina",
"Setophaga americana",
"Setophaga magnolia",
"Setophaga castanea",
"Setophaga fusca",
"Setophaga aestiva",
"Setophaga pensylvanica",
"Setophaga striata",
"Setophaga coronata",
"Cardellina pusilla",
"Dolichonyx oryzivorus",
"Icterus galbula",
"Agelaius phoeniceus",
"Molothrus ater",
"Emberiza calandra",
"Emberiza citrinella",
"Emberiza leucocephalos",
"Emberiza cia",
"Emberiza hortulana",
"Emberiza caesia",
"Emberiza cirlus",
"Emberiza fucata",
"Emberiza pusilla",
"Emberiza chrysophrys",
"Emberiza rustica",
"Emberiza aureola",
"Emberiza rutila",
"Emberiza melanocephala",
"Emberiza spodocephala",
"Emberiza pallasi",
"Emberiza schoeniclus",
"Melospiza melodia",
"Zonotrichia leucophrys",
"Zonotrichia albicollis",
"Junco hyemalis",
"Passerculus sandwichensis",
"Chondestes grammacus",
"Pipilo erythrophthalmus",
"Calcarius lapponicus",
"Plectrophenax nivalis",
"Piranga rubra",
"Piranga olivacea",
"Pheucticus ludovicianus",
"Passerina cyanea"],[
2,
5,
2,
3,
5,
5,
2,
4,
2,
4,
3,
4,
2,
4,
3,
2,
2,
5,
3,
5,
3,
4,
3,
2,
2,
5,
1,
5,
2,
2,
5,
5,
5,
5,
2,
5,
5,
2,
4,
5,
5,
4,
3,
5,
5,
4,
5,
3,
5,
3,
5,
3,
5,
4,
5,
3,
3,
5,
4,
3,
3,
2,
2,
2,
3,
1,
4,
5,
3,
4,
5,
4,
5,
5,
5,
5,
5,
3,
5,
3,
2,
5,
5,
4,
5,
5,
3,
5,
4,
5,
3,
5,
5,
2,
4,
4,
5,
4,
5,
5,
5,
3,
5,
4,
5,
5,
5,
5,
4,
2,
5,
5,
4,
5,
4,
5,
5,
2,
5,
5,
3,
2,
4,
5,
4,
5,
5,
4,
2,
4,
4,
4,
5,
5,
4,
3,
5,
4,
5,
1,
5,
5,
5,
2,
3,
5,
5,
4,
5,
5,
5,
5,
1,
1,
5,
5,
4,
4,
1,
4,
3,
2,
5,
5,
2,
5,
5,
3,
3,
5,
3,
5,
5,
5,
5,
5,
4,
5,
3,
5,
5,
2,
3,
3,
5,
3,
5,
2,
3,
4,
5,
5,
4,
4,
5,
5,
3,
3,
3,
4,
4,
5,
5,
5,
4,
4,
5,
4,
5,
2,
3,
4,
2,
5,
5,
4,
4,
4,
2,
4,
3,
5,
5,
4,
2,
4,
3,
4,
3,
5,
5,
5,
5,
5,
2,
5,
4,
5,
4,
1,
5,
5,
4,
5,
5,
3,
5,
2,
5,
2,
5,
4,
4,
1,
5,
5,
5,
5,
2,
4,
4,
5,
5,
2,
5,
5,
3,
5,
5,
5,
5,
4,
2,
2,
5,
4,
5,
5,
3,
5,
3,
5,
5,
5,
3,
3,
5,
2,
5,
5,
3,
5,
5,
1,
1,
1,
1,
5,
1,
5,
5,
5,
5,
1,
3,
5,
4,
1,
5,
3,
5,
3,
3,
5,
5,
2,
5,
5,
5,
5,
1,
5,
5,
5,
4,
3,
5,
5,
5,
4,
4,
5,
4,
1,
1,
5,
2,
5,
5,
5,
5,
3,
3,
4,
3,
3,
5,
5,
5,
5,
5,
4,
4,
5,
5,
4,
5,
5,
5,
5,
5,
5,
4,
5,
1,
1,
5,
4,
1,
1,
1,
3,
2,
3,
5,
1,
3,
2,
3,
1,
1,
5,
3,
2,
5,
1,
5,
5,
5,
5,
5,
5,
5,
2,
5,
5,
1,
5,
2,
5,
5,
2,
1,
1,
1,
5,
4,
5,
3,
5,
5,
5,
4,
4,
4,
5,
5,
5,
5,
5,
4,
5,
1,
4,
5,
1,
5,
5,
4,
5,
5,
5,
5,
5,
2,
5,
4,
4,
5,
5,
1,
2,
4,
2,
5,
5,
1,
3,
5,
5,
5,
5,
5,
5,
3,
1,
1,
1,
5,
5,
1,
5,
5,
5,
5,
5,
1,
5,
5,
5,
5,
5,
5,
5,
5,
3,
1,
5,
5,
5,
5,
5,
1,
1,
1,
1,
5,
5,
2,
5,
1,
5,
5,
5,
4,
1,
5,
5,
4,
2,
5,
4,
5,
4,
2,
5,
5,
5,
2,
2,
4,
5,
2,
5,
4,
5,
5,
5,
2,
1,
5,
2,
5,
5,
5,
1,
2,
5,
5,
2,
1,
4,
5,
5,
1,
2,
5,
4,
4,
5,
3,
2,
1,
2,
5,
3,
5,
1,
5,
4,
1,
2,
1,
3,
2,
5,
4,
5,
2,
4,
1,
5,
4,
1,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
5,
2,
1,
5,
5,
5,
5,
3,
5,
5,
5,
4,
4,
5,
4,
5,
5,
1,
5,
5,
5,
5,
5,
5,
5,
4,
4,
5,
5,
5,
5
]]
//]]>